### ISSUE TITLE
creating and deleting savedState doesn't update the "activeStates"

### ISSUE THREAD

**Issue by gouldner** [DataTables/StateRestore#4]
When you create a state it doesn't become the "active" state.
When you delete a state it is not removed from the "active" state.

You can just use the example demo to see this behavior.
https://datatables.net/extensions/staterestore/examples/customisation/activeLabel.html

Do a search on "Tokyo" and create a new state named "Tokyo".
You will notice that the state is created and it is made active but the Active State bar is NOT updated.

Now select "Tokyo" from state menu and allow the Active State bar to update with "Tokyo".
Then delete the "Tokyo" state.   Notice the active state doesn't update to none even though there are no active states.

Perhaps this just requires more triggers to "update" the Active State but I don't know what triggers to add.

**Comment by SandyDatatables** [comment]
Hi @gouldner ,

This is because the event to change the label is firing on the `draw` event, which does not occur when you save or delete a state. Take a look at [this example](http://live.datatables.net/nanuhire/1/edit) that shows how you could get this working for creation.

This won't work when removing states though. I think the best way to do this is to create an event that fires whenever a state is created, deleted or changed within StateRestore. I've raised an issue internally (DD-2398 for my reference) and will report back here when there is an update.

Thanks,
Sandy

**Comment by SandyDatatables** [comment]
Hi @gouldner ,

That should be the issue fixed now as you can see at [this example](http://live.datatables.net/fefenatu/1/edit "this example"). This will be available in the next StateRestore release which we hope will be in the next few weeks. Until then you can access the fix from the [nightly builds](https://nightly.datatables.net/staterestore/js/dataTables.stateRestore.js "nightly builds"), or from github.

Thanks,
Sandy

**Comment by gouldner** [comment]
Nice!   Really appreciate your efforts on this feature!  I have been wanting to implement saved states for quite a while but never got around to it,  It's going to make my users SO Happy!
